### ISSUE TITLE
Add "index.js" option 

### ISSUE THREAD

**Issue by yoni-g** [arminbro/generate-react-cli#16]
Hi, 

When you don't have an index.js you always need to import with double inner layer e.g.:
`import Logo from './components/Logo/Logo'`

It'll be much easier if we had an index file created in the components' directory so we can shortly import with one layer like this:
`import Logo from './components/Logo'`

Thanks! Love the tool!

**Comment by arminbro** [comment]
Hey @yoni-g,

Thanks for your request, and I'm glad to see that the GRC tool is helping you with your project. 

I've never been a fan of the extra `index.js` file pattern in each component directory.

Example of the file structure:
```
|-- /src
    |-- /components
        |-- /Logo
            |-- Logo.js
            |-- Logo.css
            |-- Logo.test.js
            |-- index.js
```

Example of the `index.js` file for the Logo component:
```jsx
export { default } from  './Logo';
```

I get that it allows for shorter import statements like this:
```jsx
import Logo from './components/Logo'
```
instead of this:
```jsx
import Logo from './components/Logo/Logo'
```

If typing fewer characters in your imports is essential, then maybe having an extra `index.js` file for every component directory might be useful.

In my opinion, I'd rather take the one extra (auto-completed) word in my import path.

I would highly recommend reading this [article](https://medium.com/hackernoon/the-100-correct-way-to-structure-a-react-app-or-why-theres-no-such-thing-3ede534ef1ed), specifically the "File naming" section.

I don't mind adding an `withIndex` option to support your need, but I think you should reconsider your pattern.

I'm going to close this ticket for now, but if you feel strongly about it, I don't mind reopening it and implementing this feature for the next release.

Cheers,
Armin

**Comment by yoni-g** [comment]
Hey @arminbro !

Really appreciate your proposal, For me this type of import is for readability reasons. I was looking for a good article about React file/project structure so I'll read it and try to see different approaches.

Thank you,
Yoni.
