### ISSUE TITLE
Add a "BUY ME A BEER/COFFEE" button

### ISSUE THREAD

**Issue by 3210jr** [arminbro/generate-react-cli#8]
Literally love this tool so much. You should add that button somewhere so that I can buy you a beer/coffee (depending your preferences I guess :) )

**Comment by arminbro** [comment]
Haha! Thank you, I appreciate that Ally. I'm just glad to hear that the CLI is helping you with your project workflow and that you're enjoying the developer experience using it. 

I've thought about enabling the sponsorship button here on GitHub but honestly, it's not necessary because it's not taking much of my time to maintain it at the moment. 

I originally built the tool because it was something we needed at my current company that I work for and I decided to open it publicly, hoping it would be helpful for other developers.

I'm going to close this ticket and I wanted to say thank you again for the compliment. Please don't hesitate to open a new ticket for any new feature requests or if you need to report any bugs you notice.

Have a great one!
Armin
